"""toggle active inactive branches

Revision ID: 090a6369768c
Revises: aff205188488
Create Date: 2025-07-25 11:02:33.917210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '090a6369768c'
down_revision = 'aff205188488'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'))
        batch_op.add_column(
            sa.Column('deactivated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('sections', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'))
        batch_op.add_column(
            sa.Column('deactivated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sections', schema=None) as batch_op:
        batch_op.drop_column('deactivated_at')
        batch_op.drop_column('is_active')

    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.drop_column('deactivated_at')
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
