"""Add is_cancelled column to Slot

Revision ID: 19b7466db06c
Revises: e9779293412f
Create Date: 2025-07-16 22:16:58.355975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19b7466db06c'
down_revision = 'e9779293412f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('slots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_cancelled', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('slots', schema=None) as batch_op:
        batch_op.drop_column('is_cancelled')

    # ### end Alembic commands ###
