"""Add role to User

Revision ID: 336fec458a34
Revises: 4f43f5812fc1
Create Date: 2025-07-01 16:35:38.081199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '336fec458a34'
down_revision = '4f43f5812fc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
