"""added user validation

Revision ID: aff205188488
Revises: 21ed199c1359
Create Date: 2025-07-24 19:32:04.363357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aff205188488'
down_revision = '21ed199c1359'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_approved', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('approval_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('registered_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('registered_at')
        batch_op.drop_column('approval_status')
        batch_op.drop_column('is_approved')

    # ### end Alembic commands ###
